import { StyleSheet } from 'react-native';
import { colors } from '../theme/colors';

export const styles = StyleSheet.create({
  card: {
    backgroundColor: colors.surface,
    borderRadius: 20,
    padding: 20,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: colors.line,
    overflow: 'hidden',
  },
  progressTrack: {
    height: 4,
    backgroundColor: colors.soft,
    marginHorizontal: -20,
    marginTop: -20,
    marginBottom: 16,
  },
  progressBar: { height: '100%', backgroundColor: colors.primary },
  instrumentTabs: { flexDirection: 'row', gap: 8, marginBottom: 12 },
  instrumentTab: {
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: colors.line,
    backgroundColor: colors.canvas,
  },
  instrumentTabActive: { backgroundColor: colors.primary, borderColor: colors.primary },
  instrumentTabText: { color: colors.muted, fontSize: 11, fontWeight: 'bold' },
  instrumentTabTextActive: { color: colors.surface },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  badge: {
    backgroundColor: colors.capriSoft,
    color: colors.primaryDark,
    fontSize: 11,
    fontWeight: 'bold',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 8,
  },
  progressPercent: { fontSize: 11, fontWeight: 'bold', color: colors.muted },
  quizBody: { gap: 8 },
  stepCount: {
    fontSize: 10,
    fontWeight: 'bold',
    color: colors.primary,
    textTransform: 'uppercase',
  },
  questionText: { fontSize: 15, fontWeight: 'bold', color: colors.ink },
  subtext: { fontSize: 11, color: colors.muted, marginBottom: 6 },
  optionsList: { gap: 8 },
  optCard: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: colors.canvas,
    padding: 12,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: colors.line,
    gap: 10,
  },
  optCardSelected: { backgroundColor: colors.primary, borderColor: colors.primary },
  optLabel: { flex: 1, fontSize: 12, fontWeight: 'bold', color: colors.ink },
  optLabelSelected: { color: colors.surface },
  badgeValue: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: colors.soft,
    alignItems: 'center',
    justifyContent: 'center',
  },
  badgeValueSelected: { backgroundColor: colors.surface },
  badgeValueText: { fontSize: 11, fontWeight: 'bold', color: colors.muted },
  badgeValueTextSelected: { color: colors.primary },
  previousButton: { paddingVertical: 8, alignSelf: 'flex-start' },
  previousButtonText: { color: colors.primary, fontSize: 11, fontWeight: 'bold' },
  optionalHeading: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  optionalBadge: {
    color: colors.muted,
    backgroundColor: colors.soft,
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 3,
    fontSize: 10,
    fontWeight: 'bold',
  },
  topicsInput: {
    minHeight: 112,
    borderWidth: 1,
    borderColor: colors.line,
    backgroundColor: colors.canvas,
    color: colors.ink,
    borderRadius: 14,
    padding: 12,
    fontSize: 12,
    lineHeight: 18,
    marginTop: 4,
  },
  characterCount: {
    color: colors.muted,
    fontSize: 10,
    textAlign: 'right',
  },
  submitButton: {
    backgroundColor: colors.primary,
    paddingVertical: 11,
    borderRadius: 12,
    alignItems: 'center',
    marginTop: 4,
  },
  submitButtonText: { color: colors.surface, fontSize: 11, fontWeight: 'bold' },
  privacyText: {
    color: colors.muted,
    fontSize: 10,
    lineHeight: 15,
    textAlign: 'center',
  },
  doneBox: {
    backgroundColor: '#F0FDF4',
    padding: 14,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#BBF7D0',
    marginTop: 8,
  },
  riskBox: { backgroundColor: '#FFF1F2', borderColor: '#FECDD3' },
  doneTitle: { fontSize: 13, fontWeight: 'bold', color: '#16A34A' },
  riskTitle: { color: '#BE123C' },
  scoreText: { fontSize: 12, fontWeight: 'bold', color: colors.ink, marginTop: 6 },
  doneText: { fontSize: 11, color: colors.muted, marginTop: 4 },
  topicsConfirmation: {
    fontSize: 11,
    color: colors.ink,
    marginTop: 8,
    lineHeight: 16,
  },
  riskText: { fontSize: 11, color: '#BE123C', marginTop: 8 },
  restartButton: {
    backgroundColor: colors.primary,
    paddingVertical: 9,
    borderRadius: 10,
    marginTop: 12,
    alignItems: 'center',
  },
  restartButtonText: { color: colors.surface, fontSize: 11, fontWeight: 'bold' },
});
