-- Captacao publica: triagem de pacientes e credenciamento de psicologos.
-- Aplicar depois do 008_seed_organizacao.sql.
--
-- Esses dois fluxos nao devem depender de arquivo local: o formulario publico
-- pode chegar pelo Vercel e a gestao pode abrir o cockpit em outro processo.
-- JSON e usado apenas para listas pequenas declaradas no formulario; os
-- registros principais continuam consultaveis e indexados no MySQL.

CREATE TABLE IF NOT EXISTS clinica_cadastros_psicologos (
  id CHAR(36) NOT NULL,
  instituicao_id CHAR(36) NOT NULL,
  organizacao_ref VARCHAR(128) NOT NULL,
  ref_core VARCHAR(128) NOT NULL,
  nome_completo VARCHAR(255) NOT NULL,
  nome_social VARCHAR(255) NULL,
  crp VARCHAR(80) NOT NULL,
  whatsapp VARCHAR(32) NOT NULL,
  email VARCHAR(255) NULL,
  cidade_uf VARCHAR(160) NULL,
  estado_uf CHAR(2) NULL,
  cidade VARCHAR(160) NULL,
  genero VARCHAR(16) NULL,
  genero_outro VARCHAR(120) NULL,
  especialidade VARCHAR(255) NULL,
  modalidade_atendimento VARCHAR(80) NULL,
  minibio TEXT NULL,
  status ENUM('EM_ANALISE','APROVADO','RECUSADO') NOT NULL DEFAULT 'EM_ANALISE',
  turnos_disponiveis JSON NOT NULL,
  modalidades_atendidas JSON NOT NULL,
  servicos_habilitados JSON NOT NULL,
  limite_pacientes_ativos INT UNSIGNED NOT NULL DEFAULT 5,
  pacientes_ativos_count INT UNSIGNED NOT NULL DEFAULT 0,
  exibir_na_vitrine TINYINT(1) NOT NULL DEFAULT 1,
  motivo_desativacao VARCHAR(255) NULL,
  ultimo_lead_recebido_em TIMESTAMP(3) NULL,
  turma_viver_mais VARCHAR(80) NULL,
  pos_graduacao_viver_mais VARCHAR(255) NULL,
  criado_em TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  atualizado_em TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  CONSTRAINT clinica_cad_psis_instituicao_fk FOREIGN KEY (instituicao_id) REFERENCES instituicoes(id),
  UNIQUE KEY clinica_cad_psis_ref_uq (instituicao_id, ref_core),
  KEY clinica_cad_psis_status_idx (instituicao_id, organizacao_ref, status),
  KEY clinica_cad_psis_crp_idx (instituicao_id, crp)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS clinica_triagens_pacientes (
  id CHAR(36) NOT NULL,
  instituicao_id CHAR(36) NOT NULL,
  organizacao_ref VARCHAR(128) NOT NULL,
  ref_core VARCHAR(128) NOT NULL,
  protocolo VARCHAR(64) NOT NULL,
  nome_paciente VARCHAR(255) NOT NULL,
  telefone VARCHAR(32) NOT NULL,
  idade VARCHAR(32) NULL,
  email VARCHAR(255) NULL,
  cpf VARCHAR(32) NULL,
  cep VARCHAR(16) NULL,
  possui_convenio VARCHAR(32) NULL,
  convenio_selecionado VARCHAR(128) NOT NULL,
  origem VARCHAR(128) NOT NULL,
  turno VARCHAR(32) NOT NULL,
  servico VARCHAR(255) NULL,
  servico_key VARCHAR(80) NULL,
  modalidade VARCHAR(80) NULL,
  genero VARCHAR(80) NULL,
  genero_outro VARCHAR(120) NULL,
  status ENUM('PENDENTE_ATRIBUICAO','AGUARDANDO_CONTATO','CONTATO_CONFIRMADO','DESISTENTE','FINALIZADO') NOT NULL,
  psicologo_alocado_id VARCHAR(128) NULL,
  psicologo_nome VARCHAR(255) NULL,
  alocado_em TIMESTAMP(3) NULL,
  confirmado_em TIMESTAMP(3) NULL,
  sla_expirado TINYINT(1) NOT NULL DEFAULT 0,
  transbordos INT UNSIGNED NOT NULL DEFAULT 0,
  psicologos_ja_tentados JSON NOT NULL,
  criado_em TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  atualizado_em TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  CONSTRAINT clinica_triagens_instituicao_fk FOREIGN KEY (instituicao_id) REFERENCES instituicoes(id),
  UNIQUE KEY clinica_triagens_ref_uq (instituicao_id, ref_core),
  UNIQUE KEY clinica_triagens_protocolo_uq (instituicao_id, protocolo),
  KEY clinica_triagens_status_idx (instituicao_id, organizacao_ref, status),
  KEY clinica_triagens_alocacao_idx (instituicao_id, psicologo_alocado_id, alocado_em)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
